version: '3'

services:
  openldap:
    build: ./ldap
    environment:
      - LDAP_ORGANISATION=MonOrganisation
      - LDAP_DOMAIN=mondomaine.com
      - LDAP_ADMIN_PASSWORD=admin
    ports:
      - "389:389"
      - "636:636"
    networks:
      app-network:
        ipv4_address: 172.29.0.5

  keycloak:
    build: ./keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - openldap
    networks:
      app-network:
        ipv4_address: 172.29.0.3
    extra_hosts:
      - "keycloak:127.0.0.1"

  flask-app:
    build: ./flask-app
    environment:
      - KEYCLOAK_URL=https://keycloak:8443
      - KEYCLOAK_REALM=mon-realm
      - KEYCLOAK_CLIENT_ID=flask-app
      - KEYCLOAK_CLIENT_SECRET=your-client-secret
      - PYTHONWARNINGS=ignore:Unverified HTTPS request
    ports:
      - "5000:5000"
    depends_on:
      - keycloak
    networks:
      app-network:
        ipv4_address: 172.29.0.4
    extra_hosts:
      - "keycloak:172.29.0.3"

  flask-app-passkey:
    build: ./flask-app-passkey
    environment:
      - KEYCLOAK_URL=https://keycloak:8443
      - KEYCLOAK_REALM=mon-realm
      - KEYCLOAK_CLIENT_ID=flask-app-passkey
      - KEYCLOAK_CLIENT_SECRET=your-passkey-client-secret
      - PYTHONWARNINGS=ignore:Unverified HTTPS request
    ports:
      - "5001:5000"
    depends_on:
      - keycloak
    networks:
      app-network:
        ipv4_address: 172.29.0.6
    extra_hosts:
      - "keycloak:172.29.0.3"

  dns-proxy:
      image: andyshinn/dnsmasq
      container_name: dns-proxy
      ports:
          - "53:53/udp"
          - "53:53/tcp"
      networks:
          app-network:
            ipv4_address: 172.29.0.2
      volumes:
          - ./dnsmasq.conf:/etc/dnsmasq.conf
      restart: always


networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/24
          gateway: 172.29.0.1

